import { Injectable } from '@angular/core';

interface AmplifyOutputs {
  custom?: { API?: { facefileApi?: { endpoint?: string } } };
}

/**
 * Resolves the deployed API Gateway endpoint from amplify_outputs.json
 * (generated by `ampx sandbox` / `ampx pipeline-deploy`, copied into
 * frontend/public/ at build/dev time — see CLAUDE.md). All 6 *.service.ts
 * files still call relative `/api/...` paths unchanged; the apiUrlInterceptor
 * (interceptors/api-url.interceptor.ts) rewrites them to this endpoint.
 */
@Injectable({ providedIn: 'root' })
export class ApiConfigService {
  private _apiUrl = '/api';

  get apiUrl(): string {
    return this._apiUrl;
  }

  async load(): Promise<void> {
    try {
      const res = await fetch('/amplify_outputs.json', { cache: 'no-store' });
      if (!res.ok) return;
      const outputs = (await res.json()) as AmplifyOutputs;
      const endpoint = outputs.custom?.API?.facefileApi?.endpoint;
      if (endpoint) this._apiUrl = endpoint.replace(/\/+$/, '');
    } catch {
      // No amplify_outputs.json available (e.g. `ng serve` without a
      // deployed sandbox) — stay on same-origin /api, which 404s until a
      // backend is wired up, same as running this app with no backend at all.
    }
  }
}
